Task5 first commit
bogdan-42/learning_python pull request #8
Opened 2024-09-25 13:43 UTC by nikbush

2024-10-09 12:05 UTC, fostfox requested changes
Overall check
 - Program works 
 - Errors handling needs to be refactored

Usability check
 - the output might be grouped accordingly to the member type to increase readability
 - the program asks twice about format (first: right after start, second: in the end during saving)

2024-10-09 12:05 UTC, fostfox commented on task5/README.md
> +   cd university_members_storage_system
Typo? There is no such folder in the repo

2024-10-09 12:05 UTC, fostfox commented on task5/university_members.py
> +        print(f"{YELLOW}1. Add member{RESET}")
Typo? "Add Student" probably?

2024-10-09 12:05 UTC, fostfox commented on task5/university_members.py
> +    def __init__(self, id: int, name: str, age: str) -> None:
Please, use the appropriate variable types to store numerical data. Example: `int` type for the `age`

2024-10-09 12:05 UTC, fostfox commented on task5/university_members.py
> +FILE = "university_members_file"
It's better to use a bit more explicit name, like: `FILE_NAME` or `FILE_PATH`. 

The name `FILE` may imply that this variable contains the file object itself.

2024-10-09 12:05 UTC, fostfox commented on task5/university_members.py
> +                    "gpa": member.gpa
Serializing of `id`, `name` and `age` fields might be maded only once (without duplication for each types). For ex.:

```python
for member in members:
    member_json = {}
    if isinstance(member, UniversityMember):
        member_json["value"] = {
            "id": member.id,
            "name": member.name,
            "age": member.age
        }
    elif:
        #...
    
    if isinstance(member, Student):
        member_json["value"].update({
            "course": member.course,
            "year": member.year,
            "gpa": member.gpa
        })
    elif:
        #....
```

2024-10-09 12:05 UTC, fostfox commented on task5/university_members.py
> +                members.remove(member)
This might look simpler:
```suggestion
                del member
```

2024-10-15 06:54 UTC, bushmakin commented on task5/university_members.py
> +    def __init__(self, id: int, name: str, age: str) -> None:
done

2024-10-15 06:54 UTC, nikbush commented on task5/university_members.py
> +FILE = "university_members_file"
done

2024-10-15 06:55 UTC, nikbush commented on task5/university_members.py
> +                    "gpa": member.gpa
done

2024-10-15 06:56 UTC, bushmakin commented on task5/university_members.py
> +                members.remove(member)
done

2024-11-01 13:18 UTC, fostfox commented on task5/university_members.py
> +        print(f"{YELLOW}1. Add member{RESET}")
Was Fixed

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +        self.gpa = gpa
выглядит так, как будто можно воспользоваться пакетом dataclasses для определения моделей

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +        member_json = {}
Можно пойти дальше при использовании аннтоций и добавить определение классов, которые могут быть в этом списке list[UniversityMember], например

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +            members_json.append(member_json)
Думаю, что стоит определить в родительском классе функцию, которая будет сериализовать объект в json, а здесь просто вызывать ее. В итоге ты сможешь упростить свою функцию, цель которой будет пройтись по массиву и серрилизовать его в json, вызвав одну функцию.

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +            })
Конвертацию полей класса можно реализовать через "магический" метод класса __dict__ и выполнять приведение к dict через dict(member)

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +    return members
Можно подумать над эффективностью чтения из файла в динамически расширяемый масссив

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +    return next_id
Я считаю, что докстрока для такой простой функции излишек. Также название функции и дока плохо отражают логику. Возможно более удачным решением будет next_id() или next_uq_id()

Почему неиспользуемые, они точно ранее использовались? Почему генерация, если ты считаешь? 

Также можно рассмотреть вопрос произоводительности: можно просто увеличивать значение пока не произойдет переполнение  int типа, а вот потом искать свободное, конечно, если список отсортирован.

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +    return
Определяй расширение файла, используя пакет os.path, или бросай исключение и отлавливай в точке входа

Некорректно пробовать загрузить файл, чтобы определить его формат, а если файл будет весить несколько гб? В данных функциях или возвращай файл или измени названия и алгоритм

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +            remove_member_by_id(members)
Мне кажется, что members стоит выделить в отдельный класс с методами  add(member UniversityMember, type str), remove(id int)  и тп

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +        print(f"\n{RED}\nProgram interrupted by user. Exiting...{RESET}")
Если программа будет завершенна внезапно, а не стандартным методом, то произойдет потеря данных - это корректное поведение?

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +        print("You cannot enter symbols!")
Стоит member держать отсортированным, а здесь искать id бинарным методом

2024-11-01 18:47 UTC, aboogi commented on task5/university_members.py
> +        return members
Почему массив? Почему не словарь (требований к хранению не увидел)?
Это просто массив? Если это просто увеличивающийся массив, то можно подумать над тем, чтобы хранить как дерево внутри массива, например, куча.

2024-11-14 21:01 UTC, fostfox approved these changes

2024-11-19 12:23 UTC, merged